zfs destroy -r "zroot/home@7daysago"
zfs rename -r "zroot/home@6daysago" "@7daysago"
zfs rename -r "zroot/home@5daysago" "@6daysago"
zfs rename -r "zroot/home@4daysago" "@5daysago"
zfs rename -r "zroot/home@3daysago" "@4daysago"
zfs rename -r "zroot/home@2daysago" "@3daysago"
zfs rename -r "zroot/home@yesterday" "@2daysago"
zfs rename -r "zroot/home@today" "@yesterday"
zfs snapshot -r "zroot/home@today"

